### ISSUE TITLE
Error when trying to build frontend

### ISSUE THREAD

**Issue by Spookyguy** [cesarrew/angular-wildfly-basic-seed#1]
Hi, 

i am trying to get the seed running, but when start npm run build, it crashes with the following output:

$ npm run build

> example@0.0.1-SNAPSHOT build D:\Projekte\AircraftManager\src\main\angular
> del -f '../webapp/**/*' '!../webapp/WEB-INF/**' && webpack --config config/webpack.prod.js --progress --profile --bail && mvn -f ../../../pom.xml clean package

Ung▒ltige Option - "webapp".
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! example@0.0.1-SNAPSHOT build: `del -f '../webapp/**/*' '!../webapp/WEB-INF/**' && webpack --config config/webpack.prod.js --progress --profile --bail && mvn -f ../../../pom.xml clean package`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the example@0.0.1-SNAPSHOT build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Frank\AppData\Roaming\npm-cache\_logs\2018-09-16T14_08_53_168Z-debug.log

**Comment by Spookyguy** [comment]
Problem no. 1 solved by exchanging 'del' with rm. Now webpack starts but throws the next error:

$ npm run build

> example@0.0.1-SNAPSHOT build D:\Projekte\AircraftManager\src\main\angular
> rm -f '../webapp/**/*' '!../webapp/WEB-INF/**' && webpack --config config/webpack.prod.js --progress --profile --bail && mvn -f ../../../pom.xml clean package

 10% building modules 3/5 modules 2 active ...r\node_modules\core-js\es7\reflect.jsModuleNotFoundError: Module not found: Error: Can't resolve './ngfactory/src/app/app.module.ngfactory' in 'D:\Projekte\AircraftManager\src\main\angular\src'
    at factoryCallback (D:\Projekte\AircraftManager\src\main\angular\node_modules\webpack\lib\Compilation.js:260:39)
    at D:\Projekte\AircraftManager\src\main\angular\node_modules\webpack\lib\NormalModuleFactory.js:243:19
    at onDoneResolving (D:\Projekte\AircraftManager\src\main\angular\node_modules\webpack\lib\NormalModuleFactory.js:59:20)
    at D:\Projekte\AircraftManager\src\main\angular\node_modules\webpack\lib\NormalModuleFactory.js:132:20
    at D:\Projekte\AircraftManager\src\main\angular\node_modules\async\dist\async.js:3888:9
    at D:\Projekte\AircraftManager\src\main\angular\node_modules\async\dist\async.js:473:16
    at iteratorCallback (D:\Projekte\AircraftManager\src\main\angular\node_modules\async\dist\async.js:1062:13)
    at D:\Projekte\AircraftManager\src\main\angular\node_modules\async\dist\async.js:969:16
    at D:\Projekte\AircraftManager\src\main\angular\node_modules\async\dist\async.js:3885:13
    at D:\Projekte\AircraftManager\src\main\angular\node_modules\webpack\lib\NormalModuleFactory.js:124:22
    at onError (D:\Projekte\AircraftManager\src\main\angular\node_modules\enhanced-resolve\lib\Resolver.js:65:10)
    at loggingCallbackWrapper (D:\Projekte\AircraftManager\src\main\angular\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at runAfter (D:\Projekte\AircraftManager\src\main\angular\node_modules\enhanced-resolve\lib\Resolver.js:158:4)
    at innerCallback (D:\Projekte\AircraftManager\src\main\angular\node_modules\enhanced-resolve\lib\Resolver.js:146:3)
    at loggingCallbackWrapper (D:\Projekte\AircraftManager\src\main\angular\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (D:\Projekte\AircraftManager\src\main\angular\node_modules\tapable\lib\Tapable.js:252:11)
    at D:\Projekte\AircraftManager\src\main\angular\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (D:\Projekte\AircraftManager\src\main\angular\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at runAfter (D:\Projekte\AircraftManager\src\main\angular\node_modules\enhanced-resolve\lib\Resolver.js:158:4)
    at innerCallback (D:\Projekte\AircraftManager\src\main\angular\node_modules\enhanced-resolve\lib\Resolver.js:146:3)
    at loggingCallbackWrapper (D:\Projekte\AircraftManager\src\main\angular\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (D:\Projekte\AircraftManager\src\main\angular\node_modules\tapable\lib\Tapable.js:252:11)
    at innerCallback (D:\Projekte\AircraftManager\src\main\angular\node_modules\enhanced-resolve\lib\Resolver.js:144:11)
    at loggingCallbackWrapper (D:\Projekte\AircraftManager\src\main\angular\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (D:\Projekte\AircraftManager\src\main\angular\node_modules\tapable\lib\Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (D:\Projekte\AircraftManager\src\main\angular\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:44:6)
    at loggingCallbackWrapper (D:\Projekte\AircraftManager\src\main\angular\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at afterInnerCallback (D:\Projekte\AircraftManager\src\main\angular\node_modules\enhanced-resolve\lib\Resolver.js:168:10)
    at loggingCallbackWrapper (D:\Projekte\AircraftManager\src\main\angular\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (D:\Projekte\AircraftManager\src\main\angular\node_modules\tapable\lib\Tapable.js:252:11)
resolve './ngfactory/src/app/app.module.ngfactory' in 'D:\Projekte\AircraftManager\src\main\angular\src'
  using description file: D:\Projekte\AircraftManager\src\main\angular\package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\Projekte\AircraftManager\src\main\angular\package.json (relative path: ./src)
    using description file: D:\Projekte\AircraftManager\src\main\angular\package.json (relative path: ./src/ngfactory/src/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\Projekte\AircraftManager\src\main\angular\src\ngfactory\src\app\app.module.ngfactory doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\Projekte\AircraftManager\src\main\angular\src\ngfactory\src\app\app.module.ngfactory.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\Projekte\AircraftManager\src\main\angular\src\ngfactory\src\app\app.module.ngfactory.ts doesn't exist
      as directory
        D:\Projekte\AircraftManager\src\main\angular\src\ngfactory\src\app\app.module.ngfactory doesn't exist
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! example@0.0.1-SNAPSHOT build: `rm -f '../webapp/**/*' '!../webapp/WEB-INF/**' && webpack --config config/webpack.prod.js --progress --profile --bail && mvn -f ../../../pom.xml clean package`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the example@0.0.1-SNAPSHOT build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Frank\AppData\Roaming\npm-cache\_logs\2018-09-16T17_40_30_581Z-debug.log
